### ISSUE TITLE
Case study

### ISSUE THREAD

**Issue by sofer** [CYPIAPT-LNDSE/breathing-with-kitty#128]
We need:
- The client: 
- Challenge:
- Solution: 
- The one-week prototype:
- The four-week MVP: 
- Technology used:

We need a very short version for now. We can do something longer when the project is completed.

**Comment by bradreeder** [comment]
The Client: Anna Freud Centre

Challenge: Young people with anxiety disorders need methods they can regularly utilise to build resilience and handle stress.

Solution: An app with offline functionality and smooth, calming design that guides the user through animated demonstrations of breathing and relaxation techniques, and can be downloaded to home screen for regular usage.

The One-Week Prototype: First game demonstrating deep abdominal breathing was built using an animated cat avatar.

The Four-Week MVP: 
  Week 1 -- PWA, IOS App Cache, Make site responsive, implement templating, optimise SVGs
  Week 2 -- Add menu landing page and more features to initial prototype: Music, timer, spoken word guided meditation, refine animations to be more instructive.
  Week 3 -- Implement a new game demonstrating a different technique, with a different avatar.
  Week 4 -- Bug fixing, wrapup.

Technology used: PWAs (Service Workers/ App Cache), Materialise CSS, Greensock.js, Webpack
