### ISSUE TITLE
how to breathe instructions

### ISSUE THREAD

**Issue by sofiapoh** [CYPIAPT-LNDSE/breathing-with-kitty#2]
As a user, I want good visual instructions about the breathing so I can breathe correctly and help my anxiety.

**Comment by CharlotteBarrett** [comment]
As a user, I want to feel reassured that the app will calm me down and provide support when I am feeling anxious.

**Comment by CharlotteBarrett** [comment]
I want a focal point so that I can focus my breath and start to breathe more easily.

**Comment by CharlotteBarrett** [comment]
As a user, I want to be able to access the breathing sync quickly and simply, without entering much information. This means that I can use it if I feel panicked and need to start the breath focus right away.
