### ISSUE TITLE
Narration and Instructions

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/breathing-with-kitty#211]
**Narration**

I think the narrative as it currently stands is well worded. Please add to the last paragraph, after ‘place your hands on your belly and breathe with me’: don’t worry if you can’t follow my breathing exactly. Just do what you can.

**Instructions**

I really like how they appear above the animation and the font is really cool. Please can we make them more frequent (aside from the two minute and five minute instructions?). Instructions should include:

• Put your hands on your belly
• Follow me
• Breathe deeply and slowly.
• Feel your belly move up and down
• Well done. That’s two minutes. 
• Remember: breathe deeply and slowly.
• Well done. You’ve been breathing deeply for five minutes now.

**Comment by bradreeder** [comment]
Hey Charlotte,

At the moment, if you click the i button on the menu a pop-up comes up that we'd reserved for more detailed breathing instructions. Would you like us to use that, so there's something they can read if they need a reminder, or do you want all instructions to be provided through the text that appears above the animation?

**Comment by CYPIAPT-admin** [comment]
I' d like the pop up to be the more detailed 'narration' part, and keep that as is with the addition of the sentence outlined above. Then i think having the instructions appear above the animation while it is in use, These are the shorter phrases outlined above. Does that make sense? thank you.

**Comment by bradreeder** [comment]
Hi Charlotte, sorry for the delay in getting back to you.  At the moment the narration part is also contained in a separate page prior to the breathing page. To clarify, would you like us to remove that page and put the narration inside the pop up on the breathing page? Thanks, working on the text instructions now. :)
