### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by sofiapoh** [CYPIAPT-LNDSE/breathing-with-kitty#217]
Charlotte needs to decide on a domain name and wether to buy one. We can help setting up based on whatever you decide.

**Comment by CharlotteBarrett** [comment]
Do you have to buy one or are free options available? What's the cost? how about:
Breathewithme.calm
Breathewith.me

**Comment by sofiapoh** [comment]
I'm not sure if there are any free domains, I think you will always have to buy one but depending on wether someone already owns it and what comes after the 'dot' determines the price. 
Someone already owns breathewith.me and '.calm' doesn't seem to be valid a TLD (top-level domain like .com .net .co.uk etc.).

**Comment by CharlotteBarrett** [comment]
I have done this with Mark this morning and he will run through the details with you this afternoon at FAC HQ. We went for breathewithme.co.uk - kind of boring but practical at least.
