### ISSUE TITLE
media queries for everything

### ISSUE THREAD

**Issue by nogainbar** [CYPIAPT-LNDSE/breathing-with-kitty#248]

**Comment by sofiapoh** [comment]
To be done ASAP:

**Breathing avatar page**
- [x]  Same placement for avatar across devices
- [x]  Scales correctly
- [x]  Tested layout on multiple phones

**Avatar carousel page**
- [x]  Same placement for avatar across devices
- [x]  Scales correctly
- [x]  Tested layout on multiple phones
