### ISSUE TITLE
re-order flow?

### ISSUE THREAD

**Issue by bradreeder** [CYPIAPT-LNDSE/breathing-with-kitty#264]
Right now the flow is: 

name page, avatar page, narration page, breathing page. 

If you click the settings icon on the breathing page you are taken to avatar page and have to read the narration page again before going to the breathing page.

Would it make sense to re-order it: name page, narration page, avatar page, breathing page? I think being asked your name and immediately then being greeted is better, and the narration page only needs to be read once on the first visit of the app?

**Comment by sofiapoh** [comment]
We can discuss this for future iterations but for now, I think we should keep it the same :)
