### ISSUE TITLE
fix bug of white flash between transitions!

### ISSUE THREAD

**Issue by nogainbar** [CYPIAPT-LNDSE/breathing-with-kitty#277]
who ever manage to get this, is a hero!

**Comment by gabrielperales** [comment]
@nogainbar I'm testing that on my laptop... and I'm not having this issue again...  I read this https://www.reddit.com/r/javascript/comments/511t69/introducing_granimjs_a_small_gradient_animation/ and I think it can be a performance issue with Granim, so maybe it is only happening sometimes.

**Comment by gabrielperales** [comment]
BTW very nice the new mountain animations!!
