### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/breathing-with-kitty#278]
Deep breathing instructions
•    Before we start, make yourself as comfortable as you can. Try to find a quiet place where you will be undisturbed.
•    You can breathe with me either sitting or lying down. If you’re sitting, put both feet flat on the ground, hip-width apart. 
•    If you’re lying down, have your legs out straight or bend your knees, so your feet are flat on the floor.
•    Put your hand on your belly and breathe in as deeply as you can. Feel how your belly moves in towards your spine, away from your hand. Now breathe out so that your belly moves back against your hand. Breathing from the belly like this is how we practice deep breathing. You can keep your hand on your belly to help you remember to breathe deeply into this area. Or you can rest your arms by your side.
•    Now follow my breathing – when I grow bigger, gently breathe in through your nose. Then, without pausing or holding your breath, breathe out through your nose or your mouth when my belly moves in. Repeat.  Allow yourself some time to get into a regular rhythm. 
•     Don’t worry if you can’t keep up. Just follow as best you can. The point is to breathe slowly and deeply from the belly as this will help you to feel calmer.
•    Keep doing this for two to five minutes. The longer you spend breathing deeply, the more calm you will feel. I will record the time and will let you know when you’ve been breathing for 5 minutes. You don’t have to stop after 5 minutes; you can keep breathing with me for as long as you like.

**Comment by bradreeder** [comment]
Hi Charlotte,

Like we spoke about earlier we've needed to trim this to fit it onto mobile.

To give you an idea the edit below is the maximum characters I can fit onto an iphone5 screen without making the user scroll.

My suggestion would be anything in the instructions to do with how to breathe itself should be moved into the prompts that appear above the breathing avatar. I'll write these up tomorrow so you can review them.

**Comment by bradreeder** [comment]
"Find a quiet place, lie on your back and bend your knees, so your feet are flat on the floor. Or, sit with both feet on the ground, hip-width apart.

Get yourself comfortable, place your hands on your belly and follow my breathing when ready. I'll guide you!

Don't worry if you can't keep up. Just breathe as slowly and deeply as you can from the belly. Allow yourself some time to get into a regular rhythm.

Do this for two to five minutes or until you feel better. The longer you breathe deeply, the calmer you will feel!"

**Comment by bradreeder** [comment]
I've modified the text in the instructions tab to this: 

"Get yourself comfortable and follow my breathing when ready. I'll guide you!

Don't worry if you can't keep up. Just breathe as slowly and deeply as you can. Allow yourself some time to get into a regular rhythm.

Keep doing this for two to five minutes or until you feel better. The longer you breathe deeply, the calmer you will feel!"

**Comment by bradreeder** [comment]
How the notifications that appear above the breathing avatar are ordered currently:

place one hand on your belly..
..and follow me..
breathe deeply and slowly..
as I grow, gently breathe in through your nose..
..and breathe out, without pause, as I shrink
on inhale, let your belly balloon out
then feel your belly shrink as your chest expands..
..and grow again as you exhale..
this is how we practice deep breathing
..one continuous motion without pause..
..deeply and slowly..
well done! that's two minutes..
it's been 5 minutes. welldone!

**Comment by CharlotteBarrett** [comment]
I like this, thanks Bradley. One change:

in the notifications that appear on screen, I think the middle section is a bit confusing. 

Please take out the lines ''on inhale, let your belly balloon out/then feel your belly shrink as your chest expands and put instead: '' on inhale, feel your belly shrink as your chest expands....and grow again as you exhale. then continue with the notifications
Do you think that make sense? It is simplified and there is only one movement of the belly for each inhale and exhale, which I think makes things clearer.

**Comment by bradreeder** [comment]
Awesome, thanks! I agree, and will update it with your change now.
