### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/breathing-with-kitty#279]
Have found something from this site: 

[http://freemusicarchive.org/music/Kevin_MacLeod/Calming/](url)

Can you double check the license please? It says creative commons and that it is free so I think it is okay to use.

**Comment by CYPIAPT-admin** [comment]
Have added music file to Github @sofiapoh

**Comment by bradreeder** [comment]
I'm unsure if @sofiapoh got around to sending you the music we spoke about earlier.

This is the artist's main page: http://freemusicarchive.org/music/Podington_Bear/

These are three we selected out, let us know if you think any of them would work: http://freemusicarchive.org/music/Podington_Bear/Melodic_Ambient/Bountiful
http://freemusicarchive.org/music/Podington_Bear/Fathomless_-_Ambient/Pink_Gradient
http://freemusicarchive.org/music/Podington_Bear/Daydream/Floating_In_Space_1506
