### ISSUE TITLE
Move closing modal arrow to top of the modal 

### ISSUE THREAD

**Issue by sofiapoh** [CYPIAPT-LNDSE/breathing-with-kitty#286]
On some browsers the arrow to close modal is GONE, I suggest we move it to the top of the page so regardless to your device, you can close it

**Comment by nogainbar** [comment]
i think its not so great tho in terms of the design because generally people will tend to look for it at the bottom of the page.

i think its better if we can possible create an option to drag to scroll down if the problem is that it disappears outside of the viewport

**Comment by nogainbar** [comment]
the other option is to move it directly underneath the text?

**Comment by bradreeder** [comment]
I'm working on the breathing menu and modal today so I'll have a think about this.
