### ISSUE TITLE
State after saving to home screen

### ISSUE THREAD

**Issue by sofiapoh** [CYPIAPT-LNDSE/breathing-with-kitty#290]
When you use the app on browser and then save it to your home screen, it remembers you have visited so it starts from the breathing page but doesn't have state because it goes straight to breathing without choosing avatar or adding name. We need something that will remember the state or start from beginning when loaded to home screen

**Comment by nogainbar** [comment]
already in issues, see issue #280

**Comment by gabrielperales** [comment]
~~You have to load the state on the `load` event https://github.com/CYPIAPT-LNDSE/breathing-with-kitty/blob/master/src/index.js#L49~~

**Comment by gabrielperales** [comment]
I said that too soon... it should be working because we are loading the state always before rendering https://github.com/CYPIAPT-LNDSE/breathing-with-kitty/blob/master/src/index.js#L29
