### ISSUE TITLE
avoid using localStorage for managing the state

### ISSUE THREAD

**Issue by gabrielperales** [CYPIAPT-LNDSE/breathing-with-kitty#294]
In some points of the application like https://github.com/CYPIAPT-LNDSE/breathing-with-kitty/blob/master/src/index.js#L50 we are using `localStorage` instead of our module to manage the state.

**Comment by MarckK** [comment]
Hi, on that line we are just checking if the user has visited the app before: we assign them a state in local storage when they visit, so we can query if it is in existence: and that determines whether or not we show them the modal by default.  How else would we determine if they had visited the site before?

**Comment by gabrielperales** [comment]
Hi @MarckK , that is alright. It can be done in that way, but we have a module so save stuff in localStorage as an unified object. The problem is that I saw that sometimes we are using `localStorage` and others `saveState`/`getState` to manage the same thing (`hasVisited`) so they are doing reference to different things.

**Comment by MarckK** [comment]
And we use that state in local storage to send them directly to the choose avatar page, if they have already visited the app.

**Comment by MarckK** [comment]
Hi, yes, we are not using 'hasVisited' saved in local storage anymore, we are just saving 'state' as an object in local storage and querying that to see if user has visited the site previously.

**Comment by MarckK** [comment]
I've pushed up a branch with that change (you can check it out)--and please let me know how you would improve it!  I trust your judgement!

**Comment by MarckK** [comment]
Also, thank you for the code review; I like that :)

**Comment by gabrielperales** [comment]
@MarckK it is always a pleasure
